### ISSUE TITLE
Prioritize a parser over another (handling overlapping parsers)

### ISSUE THREAD

**Issue by contivero** [mrkkrp/parser-combinators#16]
Is it possible to prioritize parsers in the case two or more parsers "overlap"?

For example, if I have a parser that can parse any word, and a parser that may parse only the word "a".
Then if the string is "a word", and the any-word parser parses "a", it will make the other parser fail, (because "a" has been already consumed, and "word" is not valid for the a-word parser, but yes the other way around).

This is a simplified case, mine is a bit more complex, which I might be able to fix by changing the order in which I list the parsers in the applicative chain (i.e.  `f <$> p1 <*> p2 <*> ... <*> pn`), but that is in a sense reverse engineering from whatever the implementation is under the hood. I'm fine if that ends up being the solution, but it would be nice having it at least documented.

**Comment by mrkkrp** [comment]
Sure, just use the `Alternative` instance of your parser:

```haskell
anyWord :: Parser String

aWord :: Parser String

combined :: Parser String
combined = aWord <|> anyWord
```

Depending on your parsing library and definitions of `anyWord` and `aWord` you may also need to use `try` or similar, but the idea is to use `(<|>)` and place more specific parser on the left-hand side.

**Comment by contivero** [comment]
But using `combined` with the string `"a word"` would only parse `"a"`, leaving `"word"` to be parsed (ignoring the whitespace in-between).

I'll give a concrete (real) example of what I meant. I currently have this parser working properly:

```hs
singleAnimation :: Parser Value
singleAnimation = do
    sa <- runPermutation (mkSingleAnimation
        <$> toPermutationWithDefault Nothing (try $ Just <$> (animationPlayState <* skipComments))
        <*> toPermutationWithDefault Nothing (try $ Just <$> (iterationCount <* skipComments))
        <*> toPermutationWithDefault Nothing (try $ Just <$> (time <* skipComments))
        <*> toPermutationWithDefault Nothing (try $ Just <$> (time <* skipComments))
        <*> toPermutationWithDefault Nothing (try $ Just <$> (timingFunction <* skipComments))
        <*> toPermutationWithDefault Nothing (try $ Just <$> (animationDirection <* skipComments))
        <*> toPermutationWithDefault Nothing (try $ Just <$> (animationFillMode <* skipComments))
        <*> toPermutationWithDefault Nothing (try $ Just <$> (keyframesName <* skipComments))
        )
 -- more code here
``` 

which I recently migrated from `attoparsec` + the `parsers` library. The code used to be:

```hs
singleAnimation :: Parser Value
singleAnimation = do
    sa <- permute (mkSingleAnimation <$?> (Nothing, Just <$> keyframesName <* skipComments)
      <|?> (Nothing, Just <$> iterationCount <* skipComments)
      <|?> (Nothing, Just <$> time <* skipComments)
      <|?> (Nothing, Just <$> time <* skipComments)
      <|?> (Nothing, Just <$> timingFunction <* skipComments)
      <|?> (Nothing, Just <$> animationDirection <* skipComments)
      <|?> (Nothing, Just <$> animationFillMode <* skipComments)
      <|?> (Nothing, Just <$> animationPlayState <* skipComments))
 -- more code here
```  

As you can see, it required swapping the order of `keyframesName` and `animationPlayState` parsers, because both overlap; what is valid for one tends to also be valid for the other, but one takes priority over the other (if just one word is found which is valid for both, it is assumed it's for the animation play state instead of the keyframes name).

So to answer my own question, I should order the permutation parsers according to priority, but hopefully some note could be added to the documentation regarding it.
You may close the issue!

**Comment by mrkkrp** [comment]
Ah, you should have mentioned that the question is about permutation parsers!
