### ISSUE TITLE
Permutation default field should be strict

### ISSUE THREAD

**Issue by treeowl** [mrkkrp/parser-combinators#17]
Currently,

```haskell
data Permutation m a = P (Maybe a) (m (Permutation m a))
```

It's actually impossible, given the exported functions, for the default field to be bottom or expensive to calculate, but `fmap` and `<*>` will each fill that field with a thunk. So it seems strictly better to write

```haskell
data Permutation m a = P !(Maybe a) (m (Permutation m a))
```

I don't think it's possible to make the other field strict without changing the semantics if the monad is some weird lazy thing.

**Comment by mrkkrp** [comment]
This doesn't seem to make a lot of practical difference to me. If you feel like it, open a PR and I'll merge that in.

**Comment by treeowl** [comment]
Digging in a little deeper, I have the feeling that this type may not really have the right shape at all. Consider (by way of exploration) this close relative:

```haskell
data Permutation' m a = P (m a) (m (Permutation' m a))
```

I believe that all the operations can be implemented pretty much the same with this definition, except that relevant instances of `Just` become `pure`, relevant instances of `Nothing` become `empty`, and all instances of `maybe empty pure value` become `value`.

Taking another step, this looks terribly similar to

```haskell
newtype Permutation'' m a = P (m (Either a (Permutation'' m a)))
```

(which happens to look a lot like `FreeT Identity m a` with a different `Applicative` instance). I wonder what the consequences might be?

**Comment by recursion-ninja** [comment]
I was meaning to revisit this module and determine if a different construction had better performance. I'd like to give a more in depth consideration the other constructions you've proposed. In the mean time, the associated pull request looks good to me.
