### ISSUE TITLE
count' is algorithmically inefficient

### ISSUE THREAD

**Issue by int-index** [mrkkrp/parser-combinators#6]
Looking at the definition of `count' m n`, it appears that if we successfully parsed `m+k` elements but then failed, there will also be `n-k` futile attempts:

```
count' :: Alternative m => Int -> Int -> m a -> m [a]
count' m' n' p = go m' n'
  where
    go !m !n
      | n <= 0 || m > n = pure []
      | m > 0           = (:) <$> p <*> go (m - 1) (n - 1)
      | otherwise       =
          let f t ts = maybe [] (:ts) t
          in f <$> optional p <*> go 0 (pred n)
```

For instance, if I have `count' 50 150`, and succesfully parse 51 times, then there will be 99 more attempts to parse. I think this combinator must be defined with `MonadPlus` for efficiency, to avoid these futile attempts.

**Comment by mrkkrp** [comment]
Resolved in 0fd09932fc4feeb5426e76c4d261da895a5be2c7.
